language: elixir
elixir:
- 1.3.0
env:
- MIX_ENV=travis
services:
- postgresql
deploy:
  provider: heroku
  api_key:
    secure: KNHIRM5IRdmHKJpfvwhThT9Q44M1N70KcE5llOahhmhRmoE+k8fQAGEVhtw17ElUuhAuGRBU6Z2ESAqcRDwH4u9u8uOujzhWdaYWVntgEDgyepwACoMec632kxO4u2siaXfFcZKd3/WDmCY8swkCUCB5kAg6fHGbr8jeAfeD3E/tyolUqDby3p9K+w+/EStCit3v3EUczVb0lKLgCPs9cRKGifRLQDeOh0vgqMsLxgRlItkAbtxfImQJ4A82BFufJMBaoRhAzuMTd9CVJBrCeET/xhNxb13KQ+4+2HWMMRzIJAsFtOpgcEW9qd3ECG94Hc/Q+2CoHM3lk6lte6I9T71u1DOMntzffkEuXS0/m97ko3uMP9xtep4VS3SYQg1B0SRlTheRXYyWAFfoBRDyuE1OSdEKoOxNF4nGuPm2dWrU/8kOvOllkdhYi9Dlv+yrR9w6/MvgnEbl+Z41eJOFApc/sMUzMORnkp88HSJ/xecsUxrX3Tw0oEGd2z/DphxSUMEAOSZ11Rk5zEDHM8fYxPjDG7nvsvzxy85H5btlbjSdFDAcDTSTO4qhZw9bqqySeIM6yzLWxoaYsPvPmU4J+zLVM/YK8QA2E2iU3+8ZqSu1X69kFGSK6FNwhxdhUbQr/XJBhoIGgW6mo6LVPi9LqghY6P7X31BRH9XM0DAIr00=
  app: gatherto
